---
apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: "{{ .Values.namespace }}"
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: cicd-demo
    meta.helm.sh/release-namespace: "{{ .Values.namespace }}"
stringData:
  text: This is sample data
